### ISSUE TITLE
Runtime panic has occurred using switch statement without a condition

### ISSUE THREAD

**Issue by toVersus** [yunabe/lgo#19]
ISSUE TYPE:
- Bug Report

OS / ENVIRONMENT:
- Ubuntu 16.04.3 LTS (Xenial Xerus)
- go version go1.9.2 linux/amd64
- jupyter v4.3.0
- zlib1g-dev/xenial-updates,now 1:1.2.8.dfsg-2ubuntu4.1 amd64 [installed]

SUMMARY:

When I wrote switch statement without a condition on code block in lgo notebook, runtime panic has occurred.

STEPS TO REPRODUCE:
1. Run the following code on lgo code block:

```go
import (
    "fmt"
)

n := 4
switch {
case n > 0 && n < 3:
    fmt.Println("0 < n < 3")
case n > 3 && n < 6:
    fmt.Println("3 < n < 6")
}
```

EXPECTED RESULTS:

Get the following output:

```
3 < n < 6
```

ACTUAL RESULTS:

```
panic: ast.Walk: unexpected node type <nil>

goroutine 24 [running]:
runtime/debug.Stack(0xc420afc8d0, 0x7f3b6a036000, 0xc420124650)
	/usr/lib/go-1.9/src/runtime/debug/stack.go:24 +0xa9
main.(*handlers).HandleExecuteRequest.func3.1()
	/home/ubuntu/go/src/github.com/yunabe/lgo/cmd/lgo-internal/kernel.go:161 +0x70
panic(0x7f3b6a036000, 0xc420124650)
	/usr/lib/go-1.9/src/runtime/panic.go:491 +0x294
go/ast.Walk(0x7e5fc0, 0xc420128b59, 0x0, 0x0)
	/usr/lib/go-1.9/src/go/ast/walk.go:364 +0x3144
github.com/yunabe/lgo/converter.containsCall(0x0, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/yunabe/lgo/converter/autoexit.go:23 +0x8f
github.com/yunabe/lgo/converter.isHeavyStmt(0x7e7f00, 0xc4200a45d0, 0xc420124610)
	/home/ubuntu/go/src/github.com/yunabe/lgo/converter/autoexit.go:87 +0x11e
github.com/yunabe/lgo/converter.injectAutoExitToStmt(0x7e7f00, 0xc4200a45d0, 0xc420124610, 0xc42039e801, 0x0)
	/home/ubuntu/go/src/github.com/yunabe/lgo/converter/autoexit.go:176 +0x3b
github.com/yunabe/lgo/converter.injectAutoExitToBlockStmtList(0xc4200a4638, 0x7e0001, 0xc420124610)
	/home/ubuntu/go/src/github.com/yunabe/lgo/converter/autoexit.go:163 +0x41c
github.com/yunabe/lgo/converter.injectAutoExitBlock(0xc4200a4630, 0x1, 0xc420124610)
	/home/ubuntu/go/src/github.com/yunabe/lgo/converter/autoexit.go:104 +0x4f
github.com/yunabe/lgo/converter.(*autoExitInjector).Visit(0xc420120160, 0x7e6d40, 0xc4200a4600, 0x7e5f80, 0xc420120160)
	/home/ubuntu/go/src/github.com/yunabe/lgo/converter/autoexit.go:229 +0x114
go/ast.Walk(0x7e5f80, 0xc420120160, 0x7e6d40, 0xc4200a4600)
	/usr/lib/go-1.9/src/go/ast/walk.go:52 +0x68
go/ast.walkDeclList(0x7e5f80, 0xc420120160, 0xc420331280, 0x3, 0x4)
	/usr/lib/go-1.9/src/go/ast/walk.go:38 +0x83
go/ast.Walk(0x7e5f80, 0xc420120160, 0x7e6cc0, 0xc4203d0080)
	/usr/lib/go-1.9/src/go/ast/walk.go:353 +0x2672
github.com/yunabe/lgo/converter.injectAutoExit(0x7e6cc0, 0xc4203d0080, 0xc420124610)
	/home/ubuntu/go/src/github.com/yunabe/lgo/converter/autoexit.go:220 +0x81
github.com/yunabe/lgo/converter.injectAutoExitToFile(0xc4203d0080, 0xc420331800)
	/home/ubuntu/go/src/github.com/yunabe/lgo/converter/autoexit.go:247 +0x7e
github.com/yunabe/lgo/converter.finalCheckAndRename(0xc4203d0080, 0xc420330a80, 0xc420afdbf0, 0xc4200a4600, 0xc4203d0080, 0xc420330c40, 0x0, 0x0, 0xc42010d450)
	/home/ubuntu/go/src/github.com/yunabe/lgo/converter/converter.go:1033 +0x17ad
github.com/yunabe/lgo/converter.Convert(0xc420472000, 0x75, 0xc420afdbf0, 0x0)
	/home/ubuntu/go/src/github.com/yunabe/lgo/converter/converter.go:762 +0x8a3
github.com/yunabe/lgo/cmd/runner.(*LgoRunner).Run(0xc420330640, 0x7f3b6a558dc0, 0xc420330900, 0x7e8400, 0xc4204da6a0, 0xc420472000, 0x75, 0x77d9e0, 0x778501)
	/home/ubuntu/go/src/github.com/yunabe/lgo/cmd/runner/runner.go:147 +0x55e
main.(*handlers).HandleExecuteRequest.func3(0xc420afdd30, 0xc420010810, 0x7f3b6a558dc0, 0xc420330900, 0x7e8400, 0xc4204da6a0, 0xc4204da000)
	/home/ubuntu/go/src/github.com/yunabe/lgo/cmd/lgo-internal/kernel.go:165 +0x9b
main.(*handlers).HandleExecuteRequest(0xc420010810, 0x7f3b6a558dc0, 0xc420330900, 0xc4204da000, 0xc4204da660, 0xc4204da6a0, 0xc420484000)
	/home/ubuntu/go/src/github.com/yunabe/lgo/cmd/lgo-internal/kernel.go:168 +0x39f
github.com/yunabe/lgo/jupyter/gojupyterscaffold.(*executeQueue).loop.func1(0x7f3b6a558dc0, 0xc420330880, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/yunabe/lgo/jupyter/gojupyterscaffold/execute.go:101 +0x263
github.com/yunabe/lgo/jupyter/gojupyterscaffold.(*iopubSocket).WithOngoingContext(0xc420330740, 0xc420360ef8, 0xc420490000, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/yunabe/lgo/jupyter/gojupyterscaffold/shelsocket.go:85 +0xf0
github.com/yunabe/lgo/jupyter/gojupyterscaffold.(*executeQueue).loop(0xc420330780)
	/home/ubuntu/go/src/github.com/yunabe/lgo/jupyter/gojupyterscaffold/execute.go:94 +0x223
github.com/yunabe/lgo/jupyter/gojupyterscaffold.(*Server).Loop.func2(0xc4203884e0, 0xc42033c2a0)
	/home/ubuntu/go/src/github.com/yunabe/lgo/jupyter/gojupyterscaffold/gojupyterscaffold.go:190 +0x31
created by github.com/yunabe/lgo/jupyter/gojupyterscaffold.(*Server).Loop
	/home/ubuntu/go/src/github.com/yunabe/lgo/jupyter/gojupyterscaffold/gojupyterscaffold.go:189 +0xed
```

NOTES:

This error won't appear in case of running a code with **switch true** statement (not omitting condition).

```go
import (
    "fmt"
)

n := 4
switch true {
case n > 0 && n < 3:
    fmt.Println("0 < n < 3")
case n > 3 && n < 6:
    fmt.Println("3 < n < 6")
}
```

Result:
```
3 < n < 6
```

**Comment by yunabe** [comment]
Thank you for the report, @toVersus 

I fixed the bug and updated [the latest Docker images](https://hub.docker.com/r/yunabe/lgo/tags/).
