### ISSUE TITLE
Cannot set notebook password

### ISSUE THREAD

**Issue by baram204** [yunabe/lgo#22]
When I try to set password instead of token on terminal, I got some error. (also on loginpage,)

here's errors and against.

0. out side of container. “Can not control echo on the terminal” = `docker exec -ti bash`
1. no congirugation file => type 'jupyter notebook --generate-config`
2. `ValueError: No JSON object could be decoded` => !!!!!!stuck!!!

I want to manually edit conf file using text editor... but I can't find & install them.

It's a bug, I think.

**Comment by yunabe** [comment]
I think this is the problem of jupyter notebook configuration in our prebuilt docker image (`yunabe/lgo:latest`).

Can you share the list of exact commands you run so that I can reproduce and diagnose the issue?

Thanks

**Comment by baram204** [comment]
I missed generate notebook config file.

below error is gone. now password works fine!.

```
$ jupyter notebook password
Enter password: 
Verify password: 
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/dist-packages/notebook/notebookapp.py", line 1571, in start
    super(NotebookApp, self).start()
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/usr/local/lib/python2.7/dist-packages/notebook/notebookapp.py", line 380, in start
    set_password(config_file=self.config_file)
  File "/usr/local/lib/python2.7/dist-packages/notebook/auth/security.py", line 148, in set_password
    config.NotebookApp.password = hashed_password
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/notebook/auth/security.py", line 131, in persist_config
    with io.open(config_file, 'w', encoding='utf8') as f:
IOError: [Errno 2] No such file or directory: '/home/gopher/.jupyter/jupyter_notebook_config.json'
```
