### ISSUE TITLE
Open boltDB makes kernel dead.

### ISSUE THREAD

**Issue by baram204** [yunabe/lgo#28]
Trying to opening database make kernel dead.

I install bold DB container & `log install` got `2018/02/28 06:36:17 lgo was installed in /lgo successfully
` message.

and I run below code. got kernel dead.

```
import (
	"log"

	"github.com/boltdb/bolt"
)

func main() {
	// Open the my.db data file in your current directory.
	// It will be created if it doesn't exist.
	db, err := bolt.Open("my.db", 0600, nil)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

}

main()
```

[from](https://github.com/boltdb/bolt#opening-a-database)

`my.db` file created.

I think it's not involved with file. `golang-scribble` makes dir and json file well.

**Comment by yunabe** [comment]
What happens if you replace log.Fatal with Info or fmt.Print?

**Comment by baram204** [comment]
fmt.Print(err) -> invalid argument

others ->panic: runtime error: invalid memory address or nil pointer dereference

```
invalid argument

panic: runtime error: invalid memory address or nil pointer dereference

goroutine 43 [running]:
runtime/debug.Stack(0xc400000008, 0x7faa553be490, 0xc4204d20e0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa9
github.com/yunabe/lgo/core.(*resultCounter).recordResult(0xc4204d20c8, 0x7faa552d01a0, 0x7faa556e0460)
	/go/src/github.com/yunabe/lgo/core/core.go:91 +0xce
github.com/yunabe/lgo/core.(*resultCounter).recordResultInDefer(0xc4204d20c8)
	/go/src/github.com/yunabe/lgo/core/core.go:96 +0x3b
panic(0x7faa552d01a0, 0x7faa556e0460)
	/usr/local/go/src/runtime/panic.go:491 +0x294
github.com/boltdb/bolt.(*DB).Close(0x0, 0x0, 0x0)
	/go/src/github.com/boltdb/bolt/db.go:392 +0x3a
github.com/yunabe/lgo/sess7b2274696d65223a313531393830303633303339383336363735397d/exec4.LgoExport_main()
	/go/src/github.com/yunabe/lgo/sess7b2274696d65223a313531393830303633303339383336363735397d/exec4/src.go:16 +0x79
github.com/yunabe/lgo/sess7b2274696d65223a313531393830303633303339383336363735397d/exec4.lgo_init()
	/go/src/github.com/yunabe/lgo/sess7b2274696d65223a313531393830303633303339383336363735397d/exec4/src.go:20 +0x27
github.com/yunabe/lgo/cmd/runner.loadShared.func3()
	/go/src/github.com/yunabe/lgo/cmd/runner/runner.go:60 +0x26
github.com/yunabe/lgo/core.startExec.func1(0xc4204d2090, 0xc42030ee30)
	/go/src/github.com/yunabe/lgo/core/core.go:247 +0x83
created by github.com/yunabe/lgo/core.startExec
	/go/src/github.com/yunabe/lgo/core/core.go:244 +0xcb
main routine failed
```

**Comment by baram204** [comment]
hey, I thing my dev env is the problem

I'm using docker toolobx and below isuue tells that is cause.

https://github.com/boltdb/bolt/issues/272#issuecomment-68626320

Sorry to bother you.

**Comment by yunabe** [comment]
> fmt.Print(err) -> invalid argument
Hmm.. it's weird.
Anyway, it's not a good idea to  call functions that invokes os.Exit internally in lgo because they terminate lgo kernel process. I will add a note to README.
