### ISSUE TITLE
 sql: unknown driver "postgres" (forgotten import?)

### ISSUE THREAD

**Issue by baram204** [yunabe/lgo#29]
When I try to use postgres driver Got errors below.

```
2018/03/02 02:42:04 sql: unknown driver "postgres" (forgotten import?)
panic: runtime error: invalid memory address or nil pointer dereference

goroutine 28 [running]:
runtime/debug.Stack(0xc400000008, 0x7fc528288490, 0xc42032f370)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa9
github.com/yunabe/lgo/core.(*resultCounter).recordResult(0xc42032f358, 0x7fc52819a1a0, 0x7fc5285aa460)
	/go/src/github.com/yunabe/lgo/core/core.go:91 +0xce
github.com/yunabe/lgo/core.(*resultCounter).recordResultInDefer(0xc42032f358)
	/go/src/github.com/yunabe/lgo/core/core.go:96 +0x3b
panic(0x7fc52819a1a0, 0x7fc5285aa460)
	/usr/local/go/src/runtime/panic.go:491 +0x294
database/sql.(*DB).Close(0x0, 0x22, 0x0)
	/usr/local/go/src/database/sql/sql.go:657 +0x3c
panic(0x7fc52819a1a0, 0x7fc5285aa460)
	/usr/local/go/src/runtime/panic.go:491 +0x294
database/sql.(*DB).conn(0x0, 0x7ed2c0, 0xc420332048, 0x1, 0xc420182600, 0xc42037d6d0, 0xc42038e0c0)
	/usr/local/go/src/database/sql/sql.go:930 +0x3c
database/sql.(*DB).PingContext(0x0, 0x7ed2c0, 0xc420332048, 0xc4204abf08, 0x0)
	/usr/local/go/src/database/sql/sql.go:631 +0x93
database/sql.(*DB).Ping(0x0, 0x7fc528270f80, 0x0)
	/usr/local/go/src/database/sql/sql.go:649 +0x48
github.com/yunabe/lgo/sess7b2274696d65223a313531393935383436353337313035313531397d/exec2.lgo_init()
	/go/src/github.com/yunabe/lgo/sess7b2274696d65223a313531393935383436353337313035313531397d/exec2/src.go:31 +0x262
github.com/yunabe/lgo/cmd/runner.loadShared.func3()
	/go/src/github.com/yunabe/lgo/cmd/runner/runner.go:60 +0x26
github.com/yunabe/lgo/core.startExec.func1(0xc42032f320, 0xc4201d4bf0)
	/go/src/github.com/yunabe/lgo/core/core.go:247 +0x83
created by github.com/yunabe/lgo/core.startExec
	/go/src/github.com/yunabe/lgo/core/core.go:244 +0xcb
main routine failed
```

the code is here.

```
import (
	"database/sql"
	"log"
	"os"
    
    "github.com/lib/pq"
)

	pgURL := os.Getenv("PGURL")
	if pgURL == "" {
		log.Println("PGURL empty")
	}

	db, err := sql.Open("postgres", pgURL)
	if err != nil {
		log.Println(err)
	}
	defer db.Close()

	if err := db.Ping(); err != nil {
		log.Println(err)
	}
```

- pg installed
- PGURL setted
- already `lgo install` process succesfully

```
/go/src/github.com/lib/pq$ ls
CONTRIBUTING.md  conn_test.go    issues_test.go        ssl_test.go
LICENSE.md       copy.go         notify.go             ssl_windows.go
README.md       ......

$PGURL
bash: "postgres://gopher:1111@localhost": No such file or directory
```

```
$ lgo install
2018/03/02 02:48:42 Install lgo to /lgo
....
2018/03/02 02:48:46 (16/115) Building "github.com/lib/pq"
.....
2018/03/02 02:49:01 (115/115) Building "gonum.org/v1/plot/vg/vgtex"
2018/03/02 02:49:01 Installing lgo-internal
2018/03/02 02:49:05 lgo was installed in /lgo successfully
```

How to use (postgres) database in Lgo?

**Comment by yunabe** [comment]
Can you fix this problem if you add code to access one of symbols exported in `pg`?

e.g.
```
_ = pg.Efatal
```

If you can fix this issue with this hack, I think this bug is a variant of #9.

**Comment by baram204** [comment]
Solved! 

error message gone & connect DB well.

**Comment by yunabe** [comment]
Thanks for checking it.
Then your problem was due to #9. Thank you for the report.
