### ISSUE TITLE
Compile Error in Docker 

### ISSUE THREAD

**Issue by comafire** [yunabe/lgo#64]
Hi, I've got below error when lgo compile time in docker container.
GO Version 1.9.6

Would you know why this error happened? 
Can you any help about this problem?
Thanks !!

[Error]
```
Step 26/30 : RUN lgo install
 ---> Running in 0d4fdb3e812e
2018/05/25 09:50:51 Install lgo to /lgo
2018/05/25 09:50:51 Building libstd.so
2018/05/25 09:50:59 Building lgo core package
2018/05/25 09:51:00 Building third-party packages in $GOPATH
2018/05/25 09:51:00 Installing lgo-internal
# golang.org/x/sys/unix
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x97cb3b]

goroutine 1 [running]:
cmd/compile/internal/gc.dumpasmhdr()
	/usr/local/go/src/cmd/compile/internal/gc/export.go:389 +0x2ab
cmd/compile/internal/gc.Main(0xb77130)
	/usr/local/go/src/cmd/compile/internal/gc/main.go:633 +0x280d
main.main()
	/usr/local/go/src/cmd/compile/main.go:49 +0x95
2018/05/25 09:51:02 Failed to build lgo-internal: exit status 2
```

[Dockerfile]
```
# Go
ENV GO_VERSION 1.9.6
ENV GO_OS linux
ENV GO_ARCH amd64
RUN wget https://dl.google.com/go/go$GO_VERSION.$GO_OS-$GO_ARCH.tar.gz
RUN tar -C /usr/local/ -xzf go$GO_VERSION.$GO_OS-$GO_ARCH.tar.gz
RUN mv /usr/local/go /usr/local/go-$GO_VERSION
RUN ln -s /usr/local/go-$GO_VERSION /usr/local/go
ENV PATH $PATH:/usr/local/go/bin

# Go Kernel
ENV GOPATH $HOME/go
ENV LGOPATH $HOME/lgo
ENV PATH $PATH:$GOPATH/bin:$LGOPATH/bin
RUN apt-get update && apt-get install -y --no-install-recommends \
libzmq3-dev
RUN go get github.com/yunabe/lgo/cmd/lgo && go get -d github.com/yunabe/lgo/cmd/lgo-internal
RUN lgo install
RUN python3 $(go env GOPATH)/src/github.com/yunabe/lgo/bin/install_kernel
```

**Comment by yunabe** [comment]
What is the base docker image? Can you share the entire Dockerfile?

**Comment by comafire** [comment]
Hi, I've solve this problem.

jupyter image has dependency of other base image.
I think that image has some problem.

Thanks for your attention.
