### ISSUE TITLE
strings.Builder is not available in yunabe/lgo:20190218

### ISSUE THREAD

**Issue by kortschak** [yunabe/lgo#80]
We have stabilised the graph API in gonum, so I've taken up trying your graphprac-binder with the following URL https://mybinder.org/v2/gh/yunabe/graphprac-binder/master, however it doesn't build. Failing with (briefly because mybinder doesn't allow raw, copiable text logs to be see)
```
---> Running in 607a579ad9be
# gonum,org/v1/gonum/graph/formats/dot/internal/errors
/go/src/gonum.org/v1/gonum/graph/formats/dot/internal/errors/errors.go:34:11 undefined: strings.Builder
/go/src/gonum.org/v1/gonum/graph/formats/dot/internal/errors/errors.go:55:11 undefined: strings.Builder
```

So presumably the docker image has a <go1.10 standard library. Is there a more recent version?

**Comment by yunabe** [comment]
I pushed yunabe/lgo:20190320 with go1.11.

One problem of go1.11 is lgo has a performance issue since go1.10 due to a regression in golang and the overhead of code execution is 5x slower with go1.11.

With my [Macbook Pro Late 13](https://support.apple.com/kb/sp691), the overhead is around 3 secs. The overhead can be longer if you don't use SSD.
 See https://github.com/yunabe/lgo#go110 for details and the route cause of the issue in golang.

**Comment by kortschak** [comment]
Thanks for that. Yes, I also tried another version. Yesterday I built a go1.10 lgo and tried the code I wanted to use. It was unreasonably slow.

I have that [here](https://mybinder.org/v2/gh/kortschak/graphprac-binder/master?filepath=graph-prac.ipynb).

Related: in order to get lgo to build I needed to remove main packages from the gonum tree. Otherwise I saw errors for those like this
```
panic: runtime error: index out of range

goroutine 1 [running]:
cmd/go/internal/work.(*Builder).linkSharedAction.func2(0x831da0)
        /usr/local/go/src/cmd/go/internal/work/action.go:708 +0x995
cmd/go/internal/work.(*Builder).cacheAction(0xc42011f2c0, 0xc420532f40, 0x14, 0x0, 0xc42037a150, 0xc420532f40)
        /usr/local/go/src/cmd/go/internal/work/action.go:300 +0x9f
cmd/go/internal/work.(*Builder).linkSharedAction(0xc42011f2c0, 0x1, 0x1, 0xc4200254e8, 0x6, 0xc420139680, 0xc4200254e8)
        /usr/local/go/src/cmd/go/internal/work/action.go:701 +0x29f
cmd/go/internal/work.(*Builder).buildmodeShared(0xc42011f2c0, 0x1, 0x1, 0xc42001e0d0, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc420139680, ...)
        /usr/local/go/src/cmd/go/internal/work/action.go:612 +0x12f
cmd/go/internal/work.InstallPackages(0xc42001e0d0, 0x1, 0x1, 0x0)
        /usr/local/go/src/cmd/go/internal/work/build.go:478 +0xdac
cmd/go/internal/work.runInstall(0xb01a40, 0xc42001e0d0, 0x1, 0x1)
        /usr/local/go/src/cmd/go/internal/work/build.go:412 +0x49
main.main()
        /usr/local/go/src/cmd/go/main.go:140 +0x7e1
(16/121) failed to install "gonum.org/v1/gonum/blas/testblas/benchautogen": exit status 2
```

I have asked about this on go-nuts, but have not had an answer yet. Do you know anything about this?

I also tried go1.12, but that failed completely (possibly because I have `GO111MODULE=on`).

**Comment by yunabe** [comment]
> Yesterday I built a go1.10 lgo and tried the code I wanted to use. It was unreasonably slow.

`go install` ignore prebuilt so files and all libraries your code depends on from scratch due to https://github.com/golang/go/issues/24034. So, the code execution with a lot of third-party dependencies can be extremely slow until the bug is fixed.

> Related: in order to get lgo to build I needed to remove main packages from the gonum tree. 

I committed a change to ignore main packages (https://github.com/yunabe/lgo/commit/34ba4a23def1b162bcc74ea76e7cac2358841f43).

> I also tried go1.12, but that failed completely (possibly because I have GO111MODULE=on).

Yes, I noticed the compilation of lgo is broken with go1.12. I think it's related to https://github.com/golang/go/issues/30768. But I need further investigation.

**Comment by kortschak** [comment]
Thank you for working on this.

**Comment by kortschak** [comment]
BTW I think that the gc linker should not panic no matter what the input, but I have not been able to reproduce it outside `lgo` so that I an file an issue against golang/go. Do you have any suggestions?
