### ISSUE TITLE
centos7 lgo run  error

### ISSUE THREAD

**Issue by mullerhai** [yunabe/lgo#83]
(condaEnv) [root@hzv_content_embedding bin]# lgo kernel
F0423 10:32:17.532773   22023 kernel.go:301] Failed to create a server: Failed to read : open : no such file or directory
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc0004c6000, 0xc0004300d0, 0x7a, 0xcc)
	/data/algorithm/src/github.com/golang/glog/glog.go:769 +0xd6
github.com/golang/glog.(*loggingT).output(0x5556b507eea0, 0xc000000003, 0xc000408370, 0x5556b5077f82, 0x9, 0x12d, 0x0)
	/data/algorithm/src/github.com/golang/glog/glog.go:720 +0x33c
github.com/golang/glog.(*loggingT).printf(0x5556b507eea0, 0xc000000003, 0x5556b4f613b8, 0x1d, 0xc0003dde28, 0x1, 0x1)
	/data/algorithm/src/github.com/golang/glog/glog.go:655 +0x14d
github.com/golang/glog.Fatalf(0x5556b4f613b8, 0x1d, 0xc0003dde28, 0x1, 0x1)
	/data/algorithm/src/github.com/golang/glog/glog.go:1148 +0x69
main.kernelMain(0xc000332108, 0x13, 0xc000334690)
	/data/algorithm/src/github.com/yunabe/lgo/cmd/lgo-internal/kernel.go:301 +0x200
main.main()
	/data/algorithm/src/github.com/yunabe/lgo/cmd/lgo-internal/main.go:206 +0x659
2019/04/23 10:32:17 lgo-internal failed: exit status 255

**Comment by mullerhai** [comment]
Traceback (most recent call last):
  File "/root/miniconda3/envs/condaEnv/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/root/miniconda3/envs/condaEnv/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/root/miniconda3/envs/condaEnv/lib/python3.6/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/root/miniconda3/envs/condaEnv/lib/python3.6/site-packages/notebook/services/sessions/handlers.py", line 67, in post
    model = yield gen.maybe_future(sm.get_session(path=path))
  File "/root/miniconda3/envs/condaEnv/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 170, in get_session
    return self.row_to_model(row)
  File "/root/miniconda3/envs/condaEnv/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 209, in row_to_model
    raise KeyError
KeyError
